#!/usr/bin/env python3
"""Aipim web components builder.

The component styles live in components/web/*.css, one file per component, so you can copy only what you need.
This script joins them into one file for people who want everything:

    python3 tools/build_web.py          # writes components/web/aipim-components.css
    python3 tools/build_web.py --check  # exits 1 if the joined file is out of date

Order matters: aipim-base.css first, then the components (checkbox.css defines .aipim-choice-group, which radio.css reuses).
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, 'components', 'web')
FILES = ['aipim-base.css', 'button.css', 'link.css', 'text-field.css', 'checkbox.css', 'radio.css', 'switch.css','alert.css','toast.css','empty-state.css','tag.css','card.css','top-bar.css','tab-bar.css','tabs.css','modal.css']
HEADER = ('/* Aipim design system · https://github.com/talis-galhardi/aipim · MIT License · Copyright (c) 2026 Talis Galhardi\n'
          '   Generated by tools/build_web.py from the files in components/web/: do not edit by hand.\n'
          '   Load tokens/build/css/aipim.css first. */\n')


def build():
    parts = [HEADER]
    for name in FILES:
        with open(os.path.join(WEB, name)) as f:
            body = f.read()
        lines = body.split('\n')
        if lines and lines[0].startswith('/* Aipim design system'):
            lines = lines[1:]  # drop the per-file credit line; the joined file has one at the top
        parts.append(f'\n/* ---- {name} ---- */\n' + '\n'.join(lines).strip('\n') + '\n')
    return ''.join(parts)


def main():
    out = os.path.join(WEB, 'aipim-components.css')
    text = build()
    if '--check' in sys.argv:
        current = open(out).read() if os.path.exists(out) else ''
        if current != text:
            print('components/web/aipim-components.css is out of date: run python3 tools/build_web.py')
            return 1
        print('OK: aipim-components.css is up to date')
        return 0
    with open(out, 'w') as f:
        f.write(text)
    print(f'{len(FILES)} files joined into components/web/aipim-components.css ({len(text)} bytes)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
