#!/usr/bin/env python3
"""Builds the three tutorials from tools/tutorials_content.py (the same text as the sheets of the Figma page 'Tutorials'):
    docs/en/tutorials-designers.md, docs/en/tutorials-developers.md and docs/en/tutorials-ai.md

Usage: python3 tools/build_tutorials.py            # write
       python3 tools/build_tutorials.py --check    # fail if out of date
No dependencies (Python 3.8+).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tutorials_content as W

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = ('<!-- Aipim design system · https://github.com/talis-galhardi/aipim · MIT License · Copyright (c) 2026 Talis Galhardi · '
          'Generated by tools/build_tutorials.py from tools/tutorials_content.py: do not edit by hand. -->')


def build(t):
    n = t['n']
    o = [HEADER, f'# {W.HEADINGS[n]}', '', f'*Tutorial {n} of 3 · {t["audience"]}*', '', t['lead'], '',
         '## Choose your tutorial', '', W.CHOOSE_INTRO, '', '| Tutorial | For | Where | File |', '|---|---|---|---|']
    for pn, title, aud, where, file in W.PATHS:
        mark = ' (you are here)' if pn == n else ''
        o.append(f'| {pn}. {title}{mark} | {aud} | {where} | `docs/en/{file}.md` |')
    o += ['', '## Where this fits', '', W.FIT_INTRO, '', W.FIT[n]['lead'], '', '| Stage | Name | Where it is covered |', '|---|---|---|']
    for sn, name, where in W.STAGES:
        o.append(f'| {sn} | {name} | ' + (f'**This tutorial: {W.FIT[n]["steps"][sn].lower()}**' if sn in W.FIT[n]['steps'] else where) + ' |')
    o.append('')
    if n == 1:
        o += [W.STAKEHOLDERS, '']
    o += [f'## The six steps: {t["title"]}', '', '**You need**', ''] + [f'- {x}' for x in t['need']] + ['', '**You will have**', ''] + [f'- {x}' for x in t['have']] + ['']
    for i, (title, body, code, done) in enumerate(t['steps'], 1):
        o += [f'### Step {i}: {title}', '', body, '']
        if code:
            label, lang, text = code
            o += [f'*{label}*', '', f'```{lang}', text, '```', '']
        o += [f'**Done when** {done}', '']
    o += ['### Final check', '', 'Tick every line before you move on.', ''] + [f'- [ ] {x}' for x in t['check']] + ['']
    for title, lead, cards in W.REFERENCE.get(n, []):
        o += [f'## {title}', '', lead, '']
        for over, ctitle, items in cards:
            o += [f'### {ctitle}', '', f'*{over}*', ''] + [f'- {x}' for x in items] + ['']
    if n in W.KEEP_IN:
        o += ['## Keep these close', '', W.KEEP_INTRO, '', '### Same names everywhere', '', '| In Figma | In code |', '|---|---|']
        o += [f'| {a} | {c} |' for a, c in W.NAMES]
        o += ['', '### Need something new? Ask in this order', ''] + [f'{i}. {x}' for i, x in enumerate(W.ASK, 1)] + ['', W.STUCK]
    return '\n'.join(o).rstrip() + '\n'


def outputs():
    return {f'docs/en/{file}.md': build(next(t for t in W.TUTORIALS if t['n'] == n)) for n, _, _, _, file in W.PATHS}


if __name__ == '__main__':
    out = outputs()
    old = os.path.join(ROOT, 'docs/en/tutorials.md')
    if '--check' in sys.argv:
        bad = [p for p, text in out.items() if not os.path.exists(os.path.join(ROOT, p)) or open(os.path.join(ROOT, p)).read() != text]
        if os.path.exists(old): bad.append('docs/en/tutorials.md (no longer used: delete it)')
        if bad: print('Out of date: ' + ', '.join(bad) + '. Run: python3 tools/build_tutorials.py'); sys.exit(1)
        print('OK: the three tutorials are up to date'); sys.exit(0)
    for p, text in out.items():
        open(os.path.join(ROOT, p), 'w').write(text)
    if os.path.exists(old): os.remove(old)
    print('Written: ' + ', '.join(out))
