#!/usr/bin/env python3
"""Builds docs/en/workflow.md from tools/workflow_content.py (the same text as the Figma page 'Workflow').

Usage: python3 tools/build_workflow.py            # write
       python3 tools/build_workflow.py --check    # fail if out of date
No dependencies (Python 3.8+).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import workflow_content as W

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'docs/en/workflow.md')


def build():
    o = ['<!-- Aipim design system · https://github.com/talis-galhardi/aipim · MIT License · Copyright (c) 2026 Talis Galhardi · Generated by tools/build_workflow.py from tools/workflow_content.py: do not edit by hand. -->',
         '# Workflow: stakeholders, design and engineering', '', W.INTRO, '', '## The flow at a glance', '',
         '| # | Stage | Who leads | What comes out |', '|---|---|---|---|']
    o += [f'| {i} | {s} | {w} | {out} |' for i, (s, w, out) in enumerate(W.FLOW, 1)]
    o += ['', 'After the release, what you learn goes back to stage 1.', '']
    for title, intro, blocks in W.SECTIONS:
        o += [f'## {title}', '', intro, '']
        for overline, bt, bullets in blocks:
            o += [f'### {bt}', '', f'*{overline}*', ''] + [f'- {b}' for b in bullets] + ['']
    return '\n'.join(o).rstrip() + '\n'


if __name__ == '__main__':
    text = build()
    cur = open(OUT).read() if os.path.exists(OUT) else None
    if '--check' in sys.argv:
        if cur != text: print('docs/en/workflow.md is out of date. Run: python3 tools/build_workflow.py'); sys.exit(1)
        print('OK: docs/en/workflow.md is up to date'); sys.exit(0)
    open(OUT, 'w').write(text); print('Written: docs/en/workflow.md')
