#!/usr/bin/env python3
"""Aipim token generator.

Single source: this script (color seeds at the top + scales) -> tokens/tokens.json (W3C Design Tokens 2025.10)
and, from it, CSS, Android (Compose), SwiftUI, docs/*.md and the Figma import bundle.
It also runs the accessibility checks (WCAG 2.2 contrast and color-blindness) and FAILS if anything is rejected.

Usage: python3 tools/build_tokens.py          # build everything and validate (docs in English)
       python3 tools/build_tokens.py --pt     # also build docs/pt-br/
       python3 tools/build_tokens.py --check  # validate only (writes nothing)
No dependencies (Python 3.8+).

Aipim v0.1.0 · Talis Galhardi · MIT (code) · CC BY 4.0 (design files)
"""
import json, math, os, sys

VERSION = '0.1.0'
HOME = 'https://github.com/talis-galhardi/aipim'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = f'Aipim design system v{VERSION} · {HOME} · MIT License · Copyright (c) 2026 Talis Galhardi · Generated by tools/build_tokens.py: do not edit by hand.'

# =====================================================================================
# 1. SEEDS (customize here: change hue/chroma and run again)
# =====================================================================================
SEEDS = {  # name: (OKLCH hue, base chroma, inspiration)
    'primary':   (55, 0.140, 'Clay: terracotta'),
    'secondary': (232, 0.085, 'Genipap: petrol blue'),
    'tertiary':  (82, 0.115, 'Ochre'),
    'success':   (165, 0.100, 'Leaf: moss green'),
    'error':     (14, 0.185, 'Earth red, cooler than the primary'),
}
NEUTRAL_SEED = (58, 0.016)  # almost-gray brown, tinted with earth

# =====================================================================================
# 2. COR (OKLCH → sRGB)
# =====================================================================================
def oklch_to_lin(L, C, h):
    a = C * math.cos(math.radians(h)); b = C * math.sin(math.radians(h))
    l_ = L + 0.3963377774*a + 0.2158037573*b
    m_ = L - 0.1055613458*a - 0.0638541728*b
    s_ = L - 0.0894841775*a - 1.2914855480*b
    l, m, s = l_**3, m_**3, s_**3
    return (4.0767416621*l - 3.3077115913*m + 0.2309699292*s,
            -1.2684380046*l + 2.6097574011*m - 0.3413193965*s,
            -0.0041960863*l - 0.7034186147*m + 1.7076147010*s)

def in_gamut(rgb): return all(-1e-4 <= v <= 1 + 1e-4 for v in rgb)
def enc(v):
    v = min(1, max(0, v)); return 12.92*v if v <= 0.0031308 else 1.055*v**(1/2.4) - 0.055
def to_hex(lin): return '#%02x%02x%02x' % tuple(round(enc(v)*255) for v in lin)
def from_hex(h):
    h = h.lstrip('#'); return [int(h[i:i+2], 16)/255 for i in (0, 2, 4)]
def lin(c): return c/12.92 if c <= 0.04045 else ((c+0.055)/1.055)**2.4
def lum(hexc):
    r, g, b = [lin(c) for c in from_hex(hexc)]; return 0.2126*r + 0.7152*g + 0.0722*b
def contrast(a, b):
    la, lb = lum(a), lum(b); hi, lo = max(la, lb), min(la, lb); return (hi+0.05)/(lo+0.05)
def make(L, C, h):
    c = C
    while c > 0 and not in_gamut(oklch_to_lin(L, c, h)): c -= 0.002
    return to_hex(oklch_to_lin(L, max(c, 0), h))

STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]
LIGHT = [0.975, 0.950, 0.910, 0.850, 0.770, 0.690, 0.600, 0.510, 0.420, 0.330, 0.240]
CHROMA = [0.10, 0.20, 0.38, 0.58, 0.82, 1.0, 1.0, 0.92, 0.78, 0.62, 0.46]
RAMPS = {n: {str(s): make(L, c*f, h) for s, L, f in zip(STEPS, LIGHT, CHROMA)} for n, (h, c, _) in SEEDS.items()}
NL = [0.985, 0.962, 0.925, 0.865, 0.78, 0.69, 0.585, 0.485, 0.385, 0.29, 0.20]
NC = [0.35, 0.5, 0.7, 0.85, 1.0, 1.0, 1.0, 1.0, 0.9, 0.8, 0.7]
RAMPS['neutral'] = {str(s): make(L, NEUTRAL_SEED[1]*f, NEUTRAL_SEED[0]) for s, L, f in zip(STEPS, NL, NC)}
RAMPS['neutral']['0'] = '#fffdfa'
RAMPS['neutral']['1000'] = make(0.15, 0.010, NEUTRAL_SEED[0])
RAMP_ORDER = ['primary', 'secondary', 'tertiary', 'success', 'error', 'neutral']

def R(name, step): return RAMPS[name][str(step)]

# Semantic tokens: each role points to a step of a ramp (alias), with a value for light and dark.
# (ramp, step) — the rest of the system only uses these roles.
SEMANTIC = {
 'light': {
  'bg.canvas': ('neutral', 100), 'bg.surface': ('neutral', 50), 'bg.sunken': ('neutral', 200), 'bg.scrim': ('neutral', 1000),
  'text.primary': ('neutral', 950), 'text.secondary': ('neutral', 800), 'text.muted': ('neutral', 700), 'text.inverse': ('neutral', 50),
  'border.subtle': ('neutral', 300), 'border.strong': ('neutral', 600),
  'action.primary.bg': ('primary', 800), 'action.primary.text': ('neutral', 50), 'action.primary.hover': ('primary', 900),
  'action.secondary.bg': ('secondary', 800), 'action.secondary.text': ('neutral', 50), 'action.secondary.hover': ('secondary', 900),
  'link': ('secondary', 800), 'link.visited': ('primary', 800), 'focus.ring': ('secondary', 700),
  'accent.bg': ('tertiary', 300), 'accent.text': ('neutral', 950),
  'success.bg': ('success', 100), 'success.text': ('success', 800), 'success.icon': ('success', 600),
  'warning.bg': ('tertiary', 100), 'warning.text': ('tertiary', 900), 'warning.icon': ('tertiary', 800),
  'error.bg': ('error', 100), 'error.text': ('error', 800), 'error.icon': ('error', 700),
  'info.bg': ('secondary', 100), 'info.text': ('secondary', 800), 'info.icon': ('secondary', 700)},
 'dark': {
  'bg.canvas': ('neutral', 950), 'bg.surface': ('neutral', 900), 'bg.sunken': ('neutral', 1000), 'bg.scrim': ('neutral', 1000),
  'text.primary': ('neutral', 50), 'text.secondary': ('neutral', 200), 'text.muted': ('neutral', 300), 'text.inverse': ('neutral', 950),
  'border.subtle': ('neutral', 800), 'border.strong': ('neutral', 500),
  'action.primary.bg': ('primary', 300), 'action.primary.text': ('neutral', 950), 'action.primary.hover': ('primary', 200),
  'action.secondary.bg': ('secondary', 300), 'action.secondary.text': ('neutral', 950), 'action.secondary.hover': ('secondary', 200),
  'link': ('secondary', 300), 'link.visited': ('primary', 300), 'focus.ring': ('secondary', 300),
  'accent.bg': ('tertiary', 400), 'accent.text': ('neutral', 950),
  'success.bg': ('success', 900), 'success.text': ('success', 200), 'success.icon': ('success', 200),
  'warning.bg': ('tertiary', 900), 'warning.text': ('tertiary', 200), 'warning.icon': ('tertiary', 300),
  'error.bg': ('error', 900), 'error.text': ('error', 200), 'error.icon': ('error', 400),
  'info.bg': ('secondary', 900), 'info.text': ('secondary', 200), 'info.icon': ('secondary', 400)},
}
SEM_KEYS = list(SEMANTIC['light'].keys())
SEMV = {m: {k: R(*v) for k, v in d.items()} for m, d in SEMANTIC.items()}

# =====================================================================================
# 3. NON-COLOR SCALES
# =====================================================================================
SPACE = [0, 4, 8, 12, 16, 24, 32, 48, 64, 80, 96]            # px, base 4
SPACE_ROLES = {'stack.tight': 8, 'stack.normal': 16, 'stack.loose': 24, 'inset.sm': 12, 'inset.md': 16, 'inset.lg': 24, 'inset.xl': 32, 'gap.grid': 24}
RADIUS = {'none': 0, 'sm': 4, 'md': 8, 'lg': 12, 'xl': 16, '2xl': 24, 'full': 999}
BORDER = {'thin': 1, 'medium': 2, 'thick': 3}                 # thick = focus ring width
FOCUS = {'offset': 3}                                         # gap between the element and its focus ring
SIZE = {'touch.min': 24, 'touch.comfortable': 44, 'icon.sm': 16, 'icon.md': 20, 'icon.lg': 24, 'control.sm': 32, 'control.md': 40, 'control.lg': 48}
BREAKPOINT = {'tablet': 600, 'desktop': 1024, 'wide': 1440}   # px (mobile < 600)
Z = {'base': 0, 'sticky': 100, 'dropdown': 200, 'overlay': 300, 'modal': 400, 'toast': 500}
DURATION = {'fast': 100, 'base': 200, 'slow': 320}            # ms
EASING = {'standard': (0.2, 0, 0, 1), 'enter': (0.05, 0.7, 0.1, 1), 'exit': (0.3, 0, 0.8, 0.15)}
OPACITY = {'disabled': 0.4, 'scrim': 0.5}
# shadows: list of layers (x, y, blur, spread, alpha) over each theme's base color
SHADOW_BASE = {'light': '#1a1511', 'dark': '#000000'}
SHADOWS = {
 'light': {'resting': [(0, 1, 2, 0, .08), (0, 1, 3, 0, .06)], 'raised': [(0, 4, 12, -2, .12), (0, 2, 4, -1, .06)], 'overlay': [(0, 16, 32, -8, .24), (0, 8, 16, -4, .12)]},
 'dark':  {'resting': [(0, 1, 2, 0, .40), (0, 1, 3, 0, .30)], 'raised': [(0, 4, 12, -2, .50), (0, 2, 4, -1, .30)], 'overlay': [(0, 16, 32, -8, .60), (0, 8, 16, -4, .40)]},
}
# typography: name, family (heading|body), mobile size, desktop size (rem), line-height, weight, tracking (em), uppercase
TYPE = [
 ('display', 'heading', 3.0, 4.5, 1.10, 700, 0.01, True), ('h1', 'heading', 2.5, 3.5, 1.10, 700, 0.01, True),
 ('h2', 'heading', 2.0, 2.75, 1.10, 700, 0.01, True), ('h3', 'heading', 1.75, 2.0, 1.15, 700, 0.01, True),
 ('h4', 'heading', 1.375, 1.5, 1.20, 600, 0.02, True), ('body-lg', 'body', 1.125, 1.125, 1.60, 400, 0, False),
 ('body', 'body', 1.0, 1.0, 1.50, 400, 0, False), ('body-sm', 'body', 0.875, 0.875, 1.50, 400, 0, False),
 ('label', 'body', 1.0, 1.0, 1.25, 700, 0.01, False), ('overline', 'body', 0.75, 0.75, 1.50, 700, 0.08, True),
]
FONTS = {'heading': ['Antonio', 'Impact', 'sans-serif'], 'body': ['Karla', 'system-ui', 'sans-serif']}

def fl(n): return ('%g' % n)
def fluid(mo, de):
    if mo == de: return f'{fl(mo)}rem'
    slope = (de - mo) / (1280 - 360) * 16
    base = mo - slope * 360 / 16
    return f'clamp({fl(mo)}rem, {base:.3f}rem + {slope*100:.3f}vw, {fl(de)}rem)'

# =====================================================================================
# 4. ACCESSIBILITY CHECKS
# =====================================================================================
CHECKS = [
 ('text.primary','bg.canvas',7,'Body text (AAA)'), ('text.primary','bg.surface',7,'Body text on card (AAA)'),
 ('text.secondary','bg.canvas',7,'Secondary text (AAA)'), ('text.secondary','bg.surface',7,'Secondary text on card (AAA)'),
 ('text.muted','bg.canvas',4.5,'Supporting text (AA)'), ('text.muted','bg.surface',4.5,'Supporting text on card (AA)'),
 ('text.muted','bg.sunken',4.5,'Supporting text on recessed area (AA)'),
 ('border.strong','bg.canvas',3,'Field border (UI 3:1)'), ('border.strong','bg.surface',3,'Field border on card (UI 3:1)'),
 ('action.primary.text','action.primary.bg',7,'Primary button (AAA)'), ('action.primary.text','action.primary.hover',4.5,'Primary button on hover (AA)'),
 ('action.primary.bg','bg.canvas',3,'Primary button against background (UI 3:1)'), ('action.primary.bg','bg.surface',3,'Primary button on card (UI 3:1)'),
 ('action.secondary.text','action.secondary.bg',7,'Secondary button (AAA)'), ('action.secondary.text','action.secondary.hover',4.5,'Secondary button on hover (AA)'), ('action.secondary.bg','bg.canvas',3,'Secondary button against background (UI 3:1)'),
 ('link','bg.canvas',7,'Link (AAA)'), ('link','bg.surface',7,'Link on card (AAA)'), ('link.visited','bg.canvas',4.5,'Visited link (AA)'),
 ('focus.ring','bg.canvas',3,'Focus ring (3:1)'), ('focus.ring','bg.surface',3,'Focus ring on card (3:1)'),
 ('accent.text','accent.bg',7,'Text on accent (AAA)'),
 ('success.text','success.bg',7,'Success, text (AAA)'), ('success.icon','success.bg',3,'Success, icon (3:1)'),
 ('warning.text','warning.bg',7,'Warning, text (AAA)'), ('warning.icon','warning.bg',3,'Warning, icon (3:1)'),
 ('error.text','error.bg',7,'Error, text (AAA)'), ('error.icon','error.bg',3,'Error, icon (3:1)'),
 ('info.text','info.bg',7,'Info, text (AAA)'), ('info.icon','info.bg',3,'Info, icon (3:1)'),
]
CVD = {
 'protanopia':   [[0.152286,1.052583,-0.204868],[0.114503,0.786281,0.099216],[-0.003882,-0.048116,1.051998]],
 'deuteranopia': [[0.367322,0.860646,-0.227968],[0.280085,0.672501,0.047413],[-0.011820,0.042940,0.968881]],
 'tritanopia':   [[1.255528,-0.076749,-0.178779],[-0.078411,0.930809,0.147602],[0.004733,0.691367,0.303900]],
}
def to_oklab(hexc):
    r, g, b = [lin(c) for c in from_hex(hexc)]
    l = (0.4122214708*r+0.5363325363*g+0.0514459929*b)**(1/3); m = (0.2119034982*r+0.6806995451*g+0.1073969566*b)**(1/3); s = (0.0883024619*r+0.2817188376*g+0.6299787005*b)**(1/3)
    return (0.2104542553*l+0.7936177850*m-0.0040720468*s, 1.9779984951*l-2.4285922050*m+0.4505937099*s, 0.0259040371*l+0.7827717662*m-0.8086757660*s)
def sim(hexc, mat):
    c = [lin(x) for x in from_hex(hexc)]
    return to_hex([max(0, min(1, sum(mat[i][j]*c[j] for j in range(3)))) for i in range(3)])
def de(a, b): return 100*math.dist(to_oklab(a), to_oklab(b))
CVD_PAIRS = [('success.icon', 'error.icon'), ('error.icon', 'action.primary.bg'), ('warning.icon', 'success.icon'), ('action.secondary.bg', 'action.primary.bg'), ('success.icon', 'info.icon')]

def run_checks():
    res, bad = [], []
    for mode in ('light', 'dark'):
        for fg, bg, mn, why in CHECKS:
            r = contrast(SEMV[mode][fg], SEMV[mode][bg]); res.append((mode, fg, bg, mn, why, r, r >= mn))
    fails = [x for x in res if not x[6]]
    cvd = []
    for mode in ('light', 'dark'):
        for a, b in CVD_PAIRS:
            row = {'mode': mode, 'pair': f'{a} × {b}', 'normal': de(SEMV[mode][a], SEMV[mode][b])}
            for k, mat in CVD.items(): row[k] = de(sim(SEMV[mode][a], mat), sim(SEMV[mode][b], mat))
            cvd.append(row)
    cvd_bad = [r for r in cvd for k in ('normal', 'protanopia', 'deuteranopia', 'tritanopia') if r[k] < 8]
    return res, fails, cvd, cvd_bad

# =====================================================================================
# 5. OUTPUTS
# =====================================================================================
def kebab(k): return k.replace('.', '-')
def camel(k):
    p = k.replace('-', '.').split('.'); return p[0] + ''.join(x.capitalize() for x in p[1:])
def pas(k):
    r = ''.join(x.capitalize() for x in k.replace('-', '.').split('.'))
    return ('X' + r) if r[:1].isdigit() else r  # identifiers cannot start with a digit (e.g. radius 2xl -> X2xl)
def srgb_obj(hexc, alpha=None):
    o = {'colorSpace': 'srgb', 'components': [round(c, 4) for c in from_hex(hexc)], 'hex': hexc}
    if alpha is not None: o['alpha'] = alpha
    return o
def dim(v, unit='px'): return {'value': v, 'unit': unit}

def build_dtcg():
    d = {'$description': HEADER, '$extensions': {'aipim': {'version': VERSION}}, 'color': {}}
    for n in RAMP_ORDER:
        d['color'][n] = {s: {'$type': 'color', '$value': srgb_obj(v)} for s, v in sorted(RAMPS[n].items(), key=lambda kv: int(kv[0]))}
    d['space'] = {str(v): {'$type': 'dimension', '$value': dim(v)} for v in SPACE}
    d['space-role'] = {k: {'$type': 'dimension', '$value': dim(v)} for k, v in SPACE_ROLES.items()}
    d['radius'] = {k: {'$type': 'dimension', '$value': dim(v)} for k, v in RADIUS.items()}
    d['border'] = {k: {'$type': 'dimension', '$value': dim(v)} for k, v in BORDER.items()}
    d['focus'] = {k: {'$type': 'dimension', '$value': dim(v)} for k, v in FOCUS.items()}
    d['size'] = {k: {'$type': 'dimension', '$value': dim(v)} for k, v in SIZE.items()}
    d['breakpoint'] = {k: {'$type': 'dimension', '$value': dim(v)} for k, v in BREAKPOINT.items()}
    d['z'] = {k: {'$type': 'number', '$value': v} for k, v in Z.items()}
    d['duration'] = {k: {'$type': 'duration', '$value': dim(v, 'ms')} for k, v in DURATION.items()}
    d['easing'] = {k: {'$type': 'cubicBezier', '$value': list(v)} for k, v in EASING.items()}
    d['opacity'] = {k: {'$type': 'number', '$value': v} for k, v in OPACITY.items()}
    d['elevation'] = {m: {k: {'$type': 'shadow', '$value': [{'color': srgb_obj(SHADOW_BASE[m], a), 'offsetX': dim(x), 'offsetY': dim(y), 'blur': dim(b), 'spread': dim(s)} for x, y, b, s, a in layers]} for k, layers in SHADOWS[m].items()} for m in SHADOWS}
    d['semantic'] = {m: {k: {'$type': 'color', '$value': f'{{color.{r}.{s}}}', '$extensions': {'hex': SEMV[m][k]}} for k, (r, s) in SEMANTIC[m].items()} for m in SEMANTIC}
    d['font'] = {k: {'$type': 'fontFamily', '$value': v} for k, v in FONTS.items()}
    d['text'] = {n: {'family': f'{{font.{fam}}}', 'size-mobile': dim(mo, 'rem'), 'size-desktop': dim(de_, 'rem'), 'size-fluid': fluid(mo, de_), 'line-height': lh, 'weight': w, 'letter-spacing': dim(tr, 'em'), 'uppercase': up} for n, fam, mo, de_, lh, w, tr, up in TYPE}
    return d

def rgba(hexc, a):
    r, g, b = [round(c*255) for c in from_hex(hexc)]; return f'rgba({r}, {g}, {b}, {a:g})'
def css_shadow(m, k): return ', '.join(f'{x}px {y}px {b}px {s}px {rgba(SHADOW_BASE[m], a)}' for x, y, b, s, a in SHADOWS[m][k])

def build_css():
    o = [f'/* {HEADER} */', '/* Customize by overriding the --aipim-color-* variables (primitives) or the semantic roles below. Dark theme: [data-theme="dark"] or prefers-color-scheme. */', ':root{', f'  --aipim-version:"{VERSION}";']
    for n in RAMP_ORDER:
        for s, v in sorted(RAMPS[n].items(), key=lambda kv: int(kv[0])): o.append(f'  --aipim-color-{n}-{s}:{v};')
    for v in SPACE: o.append(f'  --aipim-space-{v}:{v}px;')
    for k, v in SPACE_ROLES.items(): o.append(f'  --aipim-{kebab(k)}:{v}px;')
    for k, v in RADIUS.items(): o.append(f'  --aipim-radius-{k}:{v}px;')
    for k, v in BORDER.items(): o.append(f'  --aipim-border-{k}:{v}px;')
    for k, v in FOCUS.items(): o.append(f'  --aipim-focus-{k}:{v}px;')
    for k, v in SIZE.items(): o.append(f'  --aipim-size-{kebab(k)}:{v}px;')
    for k, v in Z.items(): o.append(f'  --aipim-z-{k}:{v};')
    for k, v in DURATION.items(): o.append(f'  --aipim-duration-{k}:{v}ms;')
    for k, v in EASING.items(): o.append(f'  --aipim-ease-{k}:cubic-bezier({", ".join(fl(x) for x in v)});')
    for k, v in OPACITY.items(): o.append(f'  --aipim-opacity-{k}:{v};')
    o.append(f'  --aipim-font-heading:{", ".join(chr(34)+f+chr(34) if " " in f else f for f in FONTS["heading"])};')
    o.append(f'  --aipim-font-body:{", ".join(chr(34)+f+chr(34) if " " in f else f for f in FONTS["body"])};')
    for n, fam, mo, de_, lh, w, tr, up in TYPE:
        o += [f'  --aipim-text-{n}-size:{fluid(mo, de_)};', f'  --aipim-text-{n}-line:{lh};', f'  --aipim-text-{n}-weight:{w};', f'  --aipim-text-{n}-tracking:{fl(tr)}em;', f'  --aipim-text-{n}-transform:{"uppercase" if up else "none"};']
    def sem(m, ind):
        return [f'{ind}--aipim-{kebab(k)}:var(--aipim-color-{r}-{s});' for k, (r, s) in SEMANTIC[m].items()] + [f'{ind}--aipim-shadow-{k}:{css_shadow(m, k)};' for k in SHADOWS[m]]
    o += sem('light', '  ')
    o.append('}')
    o += ['@media (prefers-color-scheme:dark){', '  :root:not([data-theme="light"]){'] + sem('dark', '    ') + ['    color-scheme:dark;', '  }', '}']
    o += [':root[data-theme="dark"]{'] + sem('dark', '  ') + ['  color-scheme:dark;', '}']
    o += [':root[data-theme="light"]{color-scheme:light}', '@media (prefers-reduced-motion:reduce){:root{--aipim-duration-fast:0ms;--aipim-duration-base:0ms;--aipim-duration-slow:0ms}}']
    return '\n'.join(o) + '\n'

def kt_color(h): return 'Color(0xFF' + h.lstrip('#').upper() + ')'
def build_compose():
    o = [f'// {HEADER}', '// These files are GENERATED and have not been compiled in an app yet: check them in your project before use.', 'package design.aipim.tokens', '', 'import androidx.compose.ui.graphics.Color', 'import androidx.compose.ui.text.TextStyle', 'import androidx.compose.ui.text.font.FontWeight', 'import androidx.compose.ui.unit.dp', 'import androidx.compose.ui.unit.em', 'import androidx.compose.ui.unit.sp', '', 'const val AIPIM_VERSION = "' + VERSION + '"', '', '/** Primitives: use the semantic roles (AipimColors) in components, not these. */', 'object AipimPalette {']
    for n in RAMP_ORDER:
        for s, v in sorted(RAMPS[n].items(), key=lambda kv: int(kv[0])): o.append(f'    val {pas(n)}{s} = {kt_color(v)}')
    o += ['}', '', 'data class AipimColors(']
    o += [f'    val {camel(k)}: Color,' for k in SEM_KEYS]
    o[-1] = o[-1].rstrip(',')
    o += [')', '']
    for m, nm in (('light', 'AipimLightColors'), ('dark', 'AipimDarkColors')):
        o.append(f'val {nm} = AipimColors(')
        o += [f'    {camel(k)} = AipimPalette.{pas(r)}{s},' for k, (r, s) in SEMANTIC[m].items()]
        o[-1] = o[-1].rstrip(',')
        o += [')', '']
    o.append('object AipimSpace {'); o += [f'    val S{v} = {v}.dp' for v in SPACE]
    o += [f'    val {pas(k)} = {v}.dp' for k, v in SPACE_ROLES.items()]; o += ['}', '', 'object AipimRadius {']
    o += [f'    val {pas(k)} = {v}.dp' for k, v in RADIUS.items()]; o += ['}', '', 'object AipimSize {']
    o += [f'    val {pas(k)} = {v}.dp' for k, v in SIZE.items()]; o += ['}', '', 'object AipimBorder {']
    o += [f'    val {pas(k)} = {v}.dp' for k, v in BORDER.items()]; o += ['}', '', 'object AipimFocus {']
    o += [f'    val {pas(k)} = {v}.dp' for k, v in FOCUS.items()]; o += ['}', '', 'object AipimMotion {']
    o += [f'    const val Duration{pas(k)}Ms = {v}' for k, v in DURATION.items()]
    o += [f'    val Ease{pas(k)} = floatArrayOf({", ".join(fl(x)+"f" for x in v)})' for k, v in EASING.items()]
    o += ['}', '', '/** The font family (Antonio and Karla) must be bundled in the app and passed as fontFamily. */', 'object AipimType {']
    for n, fam, mo, de_, lh, w, tr, up in TYPE:
        sz = int(round(mo*16)) if mo == de_ else int(round(mo*16))
        o.append(f'    // {n}: {int(round(mo*16))}sp on mobile, {int(round(de_*16))}sp on desktop/tablet')
        o.append(f'    val {pas(n)} = TextStyle(fontSize = {sz}.sp, lineHeight = {round(sz*lh)}.sp, fontWeight = FontWeight({w}), letterSpacing = {fl(tr)}.em)')
    o += ['}']
    return '\n'.join(o) + '\n'

def sw_color(h): return 'Color(hex: 0x' + h.lstrip('#').upper() + ')'
def build_swift():
    o = [f'// {HEADER}', '// These files are GENERATED and have not been compiled in an app yet: check them in your project before use.', 'import SwiftUI', '', f'public let aipimVersion = "{VERSION}"', '', 'extension Color {', '    init(hex: UInt32) {', '        self.init(.sRGB, red: Double((hex >> 16) & 0xFF) / 255, green: Double((hex >> 8) & 0xFF) / 255, blue: Double(hex & 0xFF) / 255, opacity: 1)', '    }', '}', '', '/// Primitives: use the semantic roles (AipimColors) in components, not these.', 'public enum AipimPalette {']
    for n in RAMP_ORDER:
        for s, v in sorted(RAMPS[n].items(), key=lambda kv: int(kv[0])): o.append(f'    public static let {n}{s} = {sw_color(v)}')
    o += ['}', '', 'public struct AipimColors {']
    o += [f'    public let {camel(k)}: Color' for k in SEM_KEYS]
    o.append('}'); o.append('')
    o.append('public extension AipimColors {')
    for m in ('light', 'dark'):
        o.append(f'    static let {m} = AipimColors(')
        o += [f'        {camel(k)}: AipimPalette.{r}{s},' for k, (r, s) in SEMANTIC[m].items()]
        o[-1] = o[-1].rstrip(',')
        o.append('    )')
    o += ['    static func colors(for scheme: ColorScheme) -> AipimColors { scheme == .dark ? .dark : .light }', '}', '', 'public enum AipimSpace {']
    o += [f'    public static let s{v}: CGFloat = {v}' for v in SPACE]
    o += [f'    public static let {camel(k)}: CGFloat = {v}' for k, v in SPACE_ROLES.items()]
    o += ['}', '', 'public enum AipimRadius {']; o += [f'    public static let r{pas(k)}: CGFloat = {v}' for k, v in RADIUS.items()]
    o += ['}', '', 'public enum AipimSize {']; o += [f'    public static let {camel(k)}: CGFloat = {v}' for k, v in SIZE.items()]
    o += ['}', '', 'public enum AipimBorder {']; o += [f'    public static let {camel(k)}: CGFloat = {v}' for k, v in BORDER.items()]
    o += ['}', '', 'public enum AipimFocus {']; o += [f'    public static let {camel(k)}: CGFloat = {v}' for k, v in FOCUS.items()]
    o += ['}', '', 'public enum AipimMotion {']
    o += [f'    public static let duration{pas(k)}: Double = {v/1000:g}' for k, v in DURATION.items()]
    o += ['}', '', '/// The font family (Antonio and Karla) must be bundled in the app (Info.plist) and applied with .custom().', 'public struct AipimTextStyle {', '    public let size: CGFloat', '    public let lineHeight: CGFloat', '    public let weight: Font.Weight', '    public let tracking: CGFloat', '    public let uppercase: Bool', '}', '', 'public enum AipimType {']
    wmap = {400: '.regular', 600: '.semibold', 700: '.bold'}
    for n, fam, mo, de_, lh, w, tr, up in TYPE:
        sz = int(round(mo*16))
        o.append(f'    // {n}: {sz}pt on mobile, {int(round(de_*16))}pt on desktop/tablet')
        o.append(f'    public static let {camel(n)} = AipimTextStyle(size: {sz}, lineHeight: {round(sz*lh)}, weight: {wmap[w]}, tracking: {round(tr*sz, 2):g}, uppercase: {"true" if up else "false"})')
    o += ['}']
    return '\n'.join(o) + '\n'

I18N = {
 'pt-br': {
  'color_title': 'Cores', 'color_intro': 'Gerado de `tokens/tokens.json`. Use **só os papéis semânticos** nos componentes; os primitivos existem para gerar os papéis e para personalizar.',
  'ramps': 'Rampas (primitivos)', 'ramp': 'Rampa', 'origin': 'Origem', 'steps': 'Passos', 'neutral_origin': 'Marrom quase cinza, tingido de terra',
  'origins': {'primary': 'Clay: terracotta', 'secondary': 'Genipap: petrol blue', 'tertiary': 'Ocre', 'success': 'Leaf: moss green', 'error': 'Earth red, cooler than the primary'},
  'roles': 'Papéis semânticos', 'role': 'Papel', 'light': 'Claro', 'dark': 'Escuro', 'use': 'Uso', 'state_of': 'Estado de ',
  'uses': {'bg.canvas': 'Fundo da página', 'bg.surface': 'Cards e superfícies', 'bg.sunken': 'Áreas rebaixadas', 'bg.scrim': 'Fundo atrás de modais, usado com opacity.scrim', 'text.primary': 'Texto do corpo', 'text.secondary': 'Texto secundário', 'text.muted': 'Texto de apoio', 'text.inverse': 'Texto sobre fundo escuro', 'border.subtle': 'Divisórias decorativas', 'border.strong': 'Borda de campos e controles', 'action.primary.bg': 'Botão primário', 'action.primary.text': 'Texto do botão primário', 'action.primary.hover': 'Botão primário em hover', 'action.secondary.bg': 'Botão secundário', 'action.secondary.text': 'Texto do botão secundário', 'action.secondary.hover': 'Botão secundário em hover', 'link': 'Links', 'link.visited': 'Links visitados', 'focus.ring': 'Anel de foco', 'accent.bg': 'Destaque', 'accent.text': 'Texto sobre destaque'},
  'a11y': 'Acessibilidade (WCAG 2.2)', 'a11y_txt': '{ok} de {n} verificações passam, nos dois modos. Texto do corpo em AAA (7:1), texto de apoio em AA (4,5:1), componentes e ícones em 3:1.',
  'mode': 'Modo', 'pair': 'Par', 'ratio': 'Razão', 'min': 'Mínimo', 'on': 'sobre', 'rules': 'Regras',
  'rule_list': ['Estado nunca só por cor: sempre ícone e texto.', 'Cor de acento não é cor de texto corrido.', 'Placeholder usa `text.muted`.', 'Anel de foco de 3px, com 3px de afastamento.'],
  'type_title': 'Tipografia', 'type_intro': 'Gerado de `tokens/tokens.json`. Títulos em **Antonio** (caixa-alta), corpo em **Karla**. Tudo em `rem`, fluido entre 360px e 1280px.',
  'style': 'Estilo', 'family': 'Família', 'size': 'Celular → desktop', 'lh': 'Line-height', 'weight': 'Peso', 'tracking': 'Tracking', 'caps': ', caixa-alta',
  'type_rules': ['Corpo com `line-height` de pelo menos 1,5; títulos de pelo menos 1,1 (acentos de maiúsculas).', 'Coluna de no máximo 70 caracteres.', 'Nada essencial em 12px (`overline` é só para informação não essencial).', 'O layout não pode quebrar com o espaçamento de texto aumentado (WCAG 1.4.12).'],
  'other': 'English version', 'other_path': '../en/'},
 'en': {
  'color_title': 'Colors', 'color_intro': 'Generated from `tokens/tokens.json`. Use **only the semantic roles** in components; primitives exist to generate the roles and to customize.',
  'ramps': 'Ramps (primitives)', 'ramp': 'Ramp', 'origin': 'Origin', 'steps': 'Steps', 'neutral_origin': 'Almost-gray brown, tinted with earth',
  'origins': {'primary': 'Clay: terracotta', 'secondary': 'Genipap: petrol blue', 'tertiary': 'Ochre', 'success': 'Leaf: moss green', 'error': 'Earth red, cooler than the primary'},
  'roles': 'Semantic roles', 'role': 'Role', 'light': 'Light', 'dark': 'Dark', 'use': 'Use', 'state_of': 'State: ',
  'uses': {'bg.canvas': 'Page background', 'bg.surface': 'Cards and surfaces', 'bg.sunken': 'Recessed areas', 'bg.scrim': 'Backdrop behind modals, used with opacity.scrim', 'text.primary': 'Body text', 'text.secondary': 'Secondary text', 'text.muted': 'Supporting text', 'text.inverse': 'Text on dark backgrounds', 'border.subtle': 'Decorative dividers', 'border.strong': 'Field and control borders', 'action.primary.bg': 'Primary button', 'action.primary.text': 'Primary button text', 'action.primary.hover': 'Primary button on hover', 'action.secondary.bg': 'Secondary button', 'action.secondary.text': 'Secondary button text', 'action.secondary.hover': 'Secondary button on hover', 'link': 'Links', 'link.visited': 'Visited links', 'focus.ring': 'Focus ring', 'accent.bg': 'Highlight', 'accent.text': 'Text on highlight'},
  'a11y': 'Accessibility (WCAG 2.2)', 'a11y_txt': '{ok} of {n} checks pass, in both modes. Body text at AAA (7:1), supporting text at AA (4.5:1), components and icons at 3:1.',
  'mode': 'Mode', 'pair': 'Pair', 'ratio': 'Ratio', 'min': 'Minimum', 'on': 'on', 'rules': 'Rules',
  'rule_list': ['Never convey state by color alone: always icon and text.', 'Accent color is not a running-text color.', 'Placeholder uses `text.muted`.', 'Focus ring of 3px with a 3px offset.'],
  'type_title': 'Typography', 'type_intro': 'Generated from `tokens/tokens.json`. Headings in **Antonio** (uppercase), body in **Karla**. Everything in `rem`, fluid between 360px and 1280px.',
  'style': 'Style', 'family': 'Family', 'size': 'Mobile → desktop', 'lh': 'Line-height', 'weight': 'Weight', 'tracking': 'Tracking', 'caps': ', uppercase',
  'type_rules': ['Body `line-height` of at least 1.5; headings at least 1.1 (accents on capitals).', 'Columns at most 70 characters wide.', 'Nothing essential at 12px (`overline` is only for non-essential information).', 'The layout must not break with increased text spacing (WCAG 1.4.12).'],
  'other': 'Versão em português', 'other_path': '../pt-br/'},
}
CHECK_WHY_PT = {'Body text (AAA)': 'Texto do corpo (AAA)', 'Body text on card (AAA)': 'Texto do corpo em card (AAA)', 'Secondary text (AAA)': 'Texto secundário (AAA)', 'Secondary text on card (AAA)': 'Texto secundário em card (AAA)', 'Supporting text (AA)': 'Texto de apoio (AA)', 'Supporting text on card (AA)': 'Texto de apoio em card (AA)', 'Supporting text on recessed area (AA)': 'Texto de apoio em área rebaixada (AA)', 'Field border (UI 3:1)': 'Borda de campo (UI 3:1)', 'Field border on card (UI 3:1)': 'Borda de campo em card (UI 3:1)', 'Primary button (AAA)': 'Botão primário (AAA)', 'Primary button on hover (AA)': 'Botão primário em hover (AA)', 'Primary button against background (UI 3:1)': 'Botão primário contra o fundo (UI 3:1)', 'Primary button on card (UI 3:1)': 'Botão primário em card (UI 3:1)', 'Secondary button (AAA)': 'Botão secundário (AAA)', 'Secondary button on hover (AA)': 'Botão secundário em hover (AA)', 'Secondary button against background (UI 3:1)': 'Botão secundário contra o fundo (UI 3:1)', 'Link (AAA)': 'Link (AAA)', 'Link on card (AAA)': 'Link em card (AAA)', 'Visited link (AA)': 'Link visitado (AA)', 'Focus ring (3:1)': 'Anel de foco (3:1)', 'Focus ring on card (3:1)': 'Anel de foco em card (3:1)', 'Text on accent (AAA)': 'Texto sobre acento (AAA)', 'Success, text (AAA)': 'Sucesso, texto (AAA)', 'Success, icon (3:1)': 'Sucesso, ícone (3:1)', 'Warning, text (AAA)': 'Aviso, texto (AAA)', 'Warning, icon (3:1)': 'Aviso, ícone (3:1)', 'Error, text (AAA)': 'Erro, texto (AAA)', 'Error, icon (3:1)': 'Erro, ícone (3:1)', 'Info, text (AAA)': 'Informação, texto (AAA)', 'Info, icon (3:1)': 'Informação, ícone (3:1)'}

def build_color_md(res, cvd, lang):
    t = I18N[lang]
    o = [f'<!-- {HEADER} -->', *([f'[{t["other"]}]({t["other_path"]}color.md)', ''] if '--pt' in sys.argv else []), f'# {t["color_title"]}', '', t['color_intro'], '', f'## {t["ramps"]}', '', f'| {t["ramp"]} | {t["origin"]} | {t["steps"]} |', '|---|---|---|']
    for n in RAMP_ORDER:
        o.append(f'| `{n}` | {t["origins"].get(n, t["neutral_origin"])} | ' + ', '.join(sorted(RAMPS[n], key=int)) + ' |')
    o += ['', f'## {t["roles"]}', '', f'| {t["role"]} | {t["light"]} | {t["dark"]} | {t["use"]} |', '|---|---|---|---|']
    for k in SEM_KEYS:
        (rl, sl), (rd, sd) = SEMANTIC['light'][k], SEMANTIC['dark'][k]
        o.append(f'| `{k}` | `{rl}-{sl}` {SEMV["light"][k]} | `{rd}-{sd}` {SEMV["dark"][k]} | {t["uses"].get(k, t["state_of"] + k.split(".")[0])} |')
    ok = sum(1 for r in res if r[6])
    o += ['', f'## {t["a11y"]}', '', t['a11y_txt'].format(ok=ok, n=len(res)), '', f'| {t["mode"]} | {t["pair"]} | {t["ratio"]} | {t["min"]} |', '|---|---|---|---|']
    for m, fg, bg, mn, why, r, okk in res:
        w = why if lang == 'en' else CHECK_WHY_PT.get(why, why)
        o.append(f'| {t[m]} | {w}: `{fg}` {t["on"]} `{bg}` | {r:.2f}:1 | {mn} |')
    o += ['', f'## {t["rules"]}', ''] + ['- ' + x for x in t['rule_list']]
    return '\n'.join(o) + '\n'

def build_type_md(lang):
    t = I18N[lang]
    o = [f'<!-- {HEADER} -->', *([f'[{t["other"]}]({t["other_path"]}typography.md)', ''] if '--pt' in sys.argv else []), f'# {t["type_title"]}', '', t['type_intro'], '', f'| {t["style"]} | {t["family"]} | {t["size"]} | {t["lh"]} | {t["weight"]} | {t["tracking"]} |', '|---|---|---|---|---|---|']
    for n, fam, mo, de_, lh, w, tr, up in TYPE:
        o.append(f'| `{n}` | {FONTS[fam][0]}{t["caps"] if up else ""} | {int(round(mo*16))} → {int(round(de_*16))}px | {lh:g} | {w} | {tr:g}em |')
    o += ['', f'## {t["rules"]}', ''] + ['- ' + x for x in t['type_rules']]
    return '\n'.join(o) + '\n'

def build_figma():
    """Compact bundle to create the variables and styles in Figma."""
    return {
      'primitives': {f'color/{n}/{s}': v for n in RAMP_ORDER for s, v in sorted(RAMPS[n].items(), key=lambda kv: int(kv[0]))},
      'semantic': {m: {k.replace('.', '/'): f'color/{r}/{s}' for k, (r, s) in SEMANTIC[m].items()} for m in SEMANTIC},
      'floats': {**{f'space/{v}': v for v in SPACE}, **{f'space-role/{k}': v for k, v in SPACE_ROLES.items()}, **{f'radius/{k}': v for k, v in RADIUS.items()}, **{f'border/{k}': v for k, v in BORDER.items()}, **{f'focus/{k}': v for k, v in FOCUS.items()}, **{f'size/{k.replace(".", "-")}': v for k, v in SIZE.items()}, **{f'breakpoint/{k}': v for k, v in BREAKPOINT.items()}},
      'text': [{'name': n, 'family': FONTS[fam][0], 'mobile': int(round(mo*16)), 'desktop': int(round(de_*16)), 'lh': lh, 'weight': w, 'tracking': tr, 'upper': up} for n, fam, mo, de_, lh, w, tr, up in TYPE],
      'shadows': {m: {k: [{'x': x, 'y': y, 'blur': b, 'spread': s, 'alpha': a, 'color': SHADOW_BASE[m]} for x, y, b, s, a in layers] for k, layers in SHADOWS[m].items()} for m in SHADOWS},
    }

def write(path, text):
    full = os.path.join(ROOT, path); os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, 'w') as f: f.write(text if isinstance(text, str) else json.dumps(text, indent=2, ensure_ascii=False) + '\n')

def main():
    check_only = '--check' in sys.argv
    res, fails, cvd, cvd_bad = run_checks()
    print(f'Contrast: {len(res)} checks, {len(fails)} fail')
    for m, fg, bg, mn, why, r, ok in fails: print(f'  FALHA [{m}] {fg} on {bg}: {r:.2f} (min {mn}) — {why}')
    print('Color blindness (ΔE >= 8 = distinguishable):')
    for r in cvd: print(f"  [{r['mode']}] {r['pair']:40s} normal {r['normal']:5.1f} prot {r['protanopia']:5.1f} deut {r['deuteranopia']:5.1f} trit {r['tritanopia']:5.1f}")
    if fails or cvd_bad:
        print('REJECTED: adjust the seeds or the semantic steps.'); sys.exit(1)
    if check_only: print('OK (nothing written).'); return
    write('tokens/tokens.json', build_dtcg())
    write('tokens/build/css/aipim.css', build_css())
    write('tokens/build/compose/AipimTokens.kt', build_compose())
    write('tokens/build/swift/AipimTokens.swift', build_swift())
    write('tokens/build/figma.json', build_figma())
    langs = ('en', 'pt-br') if '--pt' in sys.argv else ('en',)  # English only by default; --pt also builds the Portuguese version
    for lang in langs:
        write(f'docs/{lang}/color.md', build_color_md(res, cvd, lang))
        write(f'docs/{lang}/typography.md', build_type_md(lang))
    print('OK: tokens/tokens.json, tokens/build/{css,compose,swift,figma}, docs/' + '+'.join(langs) + '/{color,typography}.md')

if __name__ == '__main__': main()
